import assert from "node:assert/strict";
import { readFile, stat } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(new Request("http://localhost/", { headers: { accept: "text/html" } }), { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } }, { waitUntil() {}, passThroughOnException() {} });
}

test("renders the Agile Frontier planning shell", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /Agile Frontier/);
  assert.match(html, /Know what can move next/);
  assert.match(html, /Gantt frontier/);
  assert.match(html, /Target deadline/);
  assert.match(html, /Import JSON/);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape|react-loading-skeleton/i);
});

test("ships the Go+ WebAssembly planning engine", async () => {
  const [wasm, glue, source, generated] = await Promise.all([
    stat(new URL("../public/agilefrontier.wasm", import.meta.url)),
    readFile(new URL("../public/wasm_exec.js", import.meta.url), "utf8"),
    readFile(new URL("../planner/planner.gp", import.meta.url), "utf8"),
    readFile(new URL("../planner/planner_gp.go", import.meta.url), "utf8"),
  ]);
  assert.ok(wasm.size > 1_000_000);
  assert.match(glue, /WebAssembly/);
  assert.match(source, /type PlanOutcome enum/);
  assert.match(source, /type WorkerCount refine/);
  assert.match(source, /func Schedule\(/);
  assert.match(generated, /Code generated by goplus/);
});
